symbols:
- ADA_USD_SPOT
- AVAX_USD_SPOT
- BTC_USD_SPOT
- DOGE_USD_SPOT
- ENA_USD_SPOT
- ETH_USD_SPOT
- EUR_USD_SPOT
- FARTCOIN_USD_SPOT
- LTC_USD_SPOT
- SOL_USD_SPOT
- USDC_USD_SPOT
- USDT_USD_SPOT
- XRP_USD_SPOT
